//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Actions) DeepCopyInto(out *Actions) {
	*out = *in
	if in.Community != nil {
		in, out := &in.Community, &out.Community
		*out = new(CommunityAction)
		(*in).DeepCopyInto(*out)
	}
	if in.Med != nil {
		in, out := &in.Med, &out.Med
		*out = new(MedAction)
		**out = **in
	}
	if in.AsPrepend != nil {
		in, out := &in.AsPrepend, &out.AsPrepend
		*out = new(AsPrependAction)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Actions.
func (in *Actions) DeepCopy() *Actions {
	if in == nil {
		return nil
	}
	out := new(Actions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddPaths) DeepCopyInto(out *AddPaths) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddPaths.
func (in *AddPaths) DeepCopy() *AddPaths {
	if in == nil {
		return nil
	}
	out := new(AddPaths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfiSafi) DeepCopyInto(out *AfiSafi) {
	*out = *in
	if in.PrefixLimit != nil {
		in, out := &in.PrefixLimit, &out.PrefixLimit
		*out = new(PrefixLimit)
		**out = **in
	}
	if in.AddPaths != nil {
		in, out := &in.AddPaths, &out.AddPaths
		*out = new(AddPaths)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfiSafi.
func (in *AfiSafi) DeepCopy() *AfiSafi {
	if in == nil {
		return nil
	}
	out := new(AfiSafi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyPolicy) DeepCopyInto(out *ApplyPolicy) {
	*out = *in
	if in.ExportPolicy != nil {
		in, out := &in.ExportPolicy, &out.ExportPolicy
		*out = new(PolicyAssignment)
		(*in).DeepCopyInto(*out)
	}
	if in.ImportPolicy != nil {
		in, out := &in.ImportPolicy, &out.ImportPolicy
		*out = new(PolicyAssignment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyPolicy.
func (in *ApplyPolicy) DeepCopy() *ApplyPolicy {
	if in == nil {
		return nil
	}
	out := new(ApplyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AsPrependAction) DeepCopyInto(out *AsPrependAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AsPrependAction.
func (in *AsPrependAction) DeepCopy() *AsPrependAction {
	if in == nil {
		return nil
	}
	out := new(AsPrependAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfiguration) DeepCopyInto(out *BGPConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfiguration.
func (in *BGPConfiguration) DeepCopy() *BGPConfiguration {
	if in == nil {
		return nil
	}
	out := new(BGPConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfigurationList) DeepCopyInto(out *BGPConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfigurationList.
func (in *BGPConfigurationList) DeepCopy() *BGPConfigurationList {
	if in == nil {
		return nil
	}
	out := new(BGPConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfigurationSpec) DeepCopyInto(out *BGPConfigurationSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]Neighbor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PeerGroups != nil {
		in, out := &in.PeerGroups, &out.PeerGroups
		*out = make([]PeerGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DynamicNeighbors != nil {
		in, out := &in.DynamicNeighbors, &out.DynamicNeighbors
		*out = make([]DynamicNeighbor, len(*in))
		copy(*out, *in)
	}
	if in.Vrfs != nil {
		in, out := &in.Vrfs, &out.Vrfs
		*out = make([]Vrf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicyDefinitions != nil {
		in, out := &in.PolicyDefinitions, &out.PolicyDefinitions
		*out = make([]PolicyDefinition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedSets != nil {
		in, out := &in.DefinedSets, &out.DefinedSets
		*out = make([]DefinedSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetlinkImport != nil {
		in, out := &in.NetlinkImport, &out.NetlinkImport
		*out = new(NetlinkImport)
		(*in).DeepCopyInto(*out)
	}
	if in.NetlinkExport != nil {
		in, out := &in.NetlinkExport, &out.NetlinkExport
		*out = new(NetlinkExport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfigurationSpec.
func (in *BGPConfigurationSpec) DeepCopy() *BGPConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(BGPConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfigurationStatus) DeepCopyInto(out *BGPConfigurationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.RouterIDResolutionTime != nil {
		in, out := &in.RouterIDResolutionTime, &out.RouterIDResolutionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfigurationStatus.
func (in *BGPConfigurationStatus) DeepCopy() *BGPConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(BGPConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommunityAction) DeepCopyInto(out *CommunityAction) {
	*out = *in
	if in.Communities != nil {
		in, out := &in.Communities, &out.Communities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommunityAction.
func (in *CommunityAction) DeepCopy() *CommunityAction {
	if in == nil {
		return nil
	}
	out := new(CommunityAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Conditions) DeepCopyInto(out *Conditions) {
	*out = *in
	if in.PrefixSet != nil {
		in, out := &in.PrefixSet, &out.PrefixSet
		*out = new(MatchSet)
		**out = **in
	}
	if in.NeighborSet != nil {
		in, out := &in.NeighborSet, &out.NeighborSet
		*out = new(MatchSet)
		**out = **in
	}
	if in.AsPathSet != nil {
		in, out := &in.AsPathSet, &out.AsPathSet
		*out = new(MatchSet)
		**out = **in
	}
	if in.CommunitySet != nil {
		in, out := &in.CommunitySet, &out.CommunitySet
		*out = new(MatchSet)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Conditions.
func (in *Conditions) DeepCopy() *Conditions {
	if in == nil {
		return nil
	}
	out := new(Conditions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Confederation) DeepCopyInto(out *Confederation) {
	*out = *in
	if in.MemberAsList != nil {
		in, out := &in.MemberAsList, &out.MemberAsList
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Confederation.
func (in *Confederation) DeepCopy() *Confederation {
	if in == nil {
		return nil
	}
	out := new(Confederation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultRouteDistance) DeepCopyInto(out *DefaultRouteDistance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultRouteDistance.
func (in *DefaultRouteDistance) DeepCopy() *DefaultRouteDistance {
	if in == nil {
		return nil
	}
	out := new(DefaultRouteDistance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefinedSet) DeepCopyInto(out *DefinedSet) {
	*out = *in
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Prefixes != nil {
		in, out := &in.Prefixes, &out.Prefixes
		*out = make([]Prefix, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefinedSet.
func (in *DefinedSet) DeepCopy() *DefinedSet {
	if in == nil {
		return nil
	}
	out := new(DefinedSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicNeighbor) DeepCopyInto(out *DynamicNeighbor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicNeighbor.
func (in *DynamicNeighbor) DeepCopy() *DynamicNeighbor {
	if in == nil {
		return nil
	}
	out := new(DynamicNeighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EbgpMultihop) DeepCopyInto(out *EbgpMultihop) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EbgpMultihop.
func (in *EbgpMultihop) DeepCopy() *EbgpMultihop {
	if in == nil {
		return nil
	}
	out := new(EbgpMultihop)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSpec) DeepCopyInto(out *GlobalSpec) {
	*out = *in
	if in.ListenAddresses != nil {
		in, out := &in.ListenAddresses, &out.ListenAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Families != nil {
		in, out := &in.Families, &out.Families
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RouteSelectionOptions != nil {
		in, out := &in.RouteSelectionOptions, &out.RouteSelectionOptions
		*out = new(RouteSelectionOptions)
		**out = **in
	}
	if in.DefaultRouteDistance != nil {
		in, out := &in.DefaultRouteDistance, &out.DefaultRouteDistance
		*out = new(DefaultRouteDistance)
		**out = **in
	}
	if in.Confederation != nil {
		in, out := &in.Confederation, &out.Confederation
		*out = new(Confederation)
		(*in).DeepCopyInto(*out)
	}
	if in.GracefulRestart != nil {
		in, out := &in.GracefulRestart, &out.GracefulRestart
		*out = new(GracefulRestart)
		**out = **in
	}
	if in.ApplyPolicy != nil {
		in, out := &in.ApplyPolicy, &out.ApplyPolicy
		*out = new(ApplyPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSpec.
func (in *GlobalSpec) DeepCopy() *GlobalSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulRestart) DeepCopyInto(out *GracefulRestart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GracefulRestart.
func (in *GracefulRestart) DeepCopy() *GracefulRestart {
	if in == nil {
		return nil
	}
	out := new(GracefulRestart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchSet) DeepCopyInto(out *MatchSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchSet.
func (in *MatchSet) DeepCopy() *MatchSet {
	if in == nil {
		return nil
	}
	out := new(MatchSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MedAction) DeepCopyInto(out *MedAction) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MedAction.
func (in *MedAction) DeepCopy() *MedAction {
	if in == nil {
		return nil
	}
	out := new(MedAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Neighbor) DeepCopyInto(out *Neighbor) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.AfiSafis != nil {
		in, out := &in.AfiSafis, &out.AfiSafis
		*out = make([]AfiSafi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApplyPolicy != nil {
		in, out := &in.ApplyPolicy, &out.ApplyPolicy
		*out = new(ApplyPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Timers != nil {
		in, out := &in.Timers, &out.Timers
		*out = new(Timers)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(Transport)
		**out = **in
	}
	if in.GracefulRestart != nil {
		in, out := &in.GracefulRestart, &out.GracefulRestart
		*out = new(GracefulRestart)
		**out = **in
	}
	if in.RouteReflector != nil {
		in, out := &in.RouteReflector, &out.RouteReflector
		*out = new(RouteReflector)
		**out = **in
	}
	if in.EbgpMultihop != nil {
		in, out := &in.EbgpMultihop, &out.EbgpMultihop
		*out = new(EbgpMultihop)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Neighbor.
func (in *Neighbor) DeepCopy() *Neighbor {
	if in == nil {
		return nil
	}
	out := new(Neighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeighborConfig) DeepCopyInto(out *NeighborConfig) {
	*out = *in
	if in.AuthPasswordSecretRef != nil {
		in, out := &in.AuthPasswordSecretRef, &out.AuthPasswordSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeighborConfig.
func (in *NeighborConfig) DeepCopy() *NeighborConfig {
	if in == nil {
		return nil
	}
	out := new(NeighborConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkExport) DeepCopyInto(out *NetlinkExport) {
	*out = *in
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]NetlinkExportRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkExport.
func (in *NetlinkExport) DeepCopy() *NetlinkExport {
	if in == nil {
		return nil
	}
	out := new(NetlinkExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkExportRule) DeepCopyInto(out *NetlinkExportRule) {
	*out = *in
	if in.CommunityList != nil {
		in, out := &in.CommunityList, &out.CommunityList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LargeCommunityList != nil {
		in, out := &in.LargeCommunityList, &out.LargeCommunityList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ValidateNexthop != nil {
		in, out := &in.ValidateNexthop, &out.ValidateNexthop
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkExportRule.
func (in *NetlinkExportRule) DeepCopy() *NetlinkExportRule {
	if in == nil {
		return nil
	}
	out := new(NetlinkExportRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetlinkImport) DeepCopyInto(out *NetlinkImport) {
	*out = *in
	if in.InterfaceList != nil {
		in, out := &in.InterfaceList, &out.InterfaceList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetlinkImport.
func (in *NetlinkImport) DeepCopy() *NetlinkImport {
	if in == nil {
		return nil
	}
	out := new(NetlinkImport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerGroup) DeepCopyInto(out *PeerGroup) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.AfiSafis != nil {
		in, out := &in.AfiSafis, &out.AfiSafis
		*out = make([]AfiSafi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApplyPolicy != nil {
		in, out := &in.ApplyPolicy, &out.ApplyPolicy
		*out = new(ApplyPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Timers != nil {
		in, out := &in.Timers, &out.Timers
		*out = new(Timers)
		**out = **in
	}
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(Transport)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerGroup.
func (in *PeerGroup) DeepCopy() *PeerGroup {
	if in == nil {
		return nil
	}
	out := new(PeerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerGroupConfig) DeepCopyInto(out *PeerGroupConfig) {
	*out = *in
	if in.AuthPasswordSecretRef != nil {
		in, out := &in.AuthPasswordSecretRef, &out.AuthPasswordSecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerGroupConfig.
func (in *PeerGroupConfig) DeepCopy() *PeerGroupConfig {
	if in == nil {
		return nil
	}
	out := new(PeerGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssignment) DeepCopyInto(out *PolicyAssignment) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssignment.
func (in *PolicyAssignment) DeepCopy() *PolicyAssignment {
	if in == nil {
		return nil
	}
	out := new(PolicyAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyDefinition) DeepCopyInto(out *PolicyDefinition) {
	*out = *in
	if in.Statements != nil {
		in, out := &in.Statements, &out.Statements
		*out = make([]Statement, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyDefinition.
func (in *PolicyDefinition) DeepCopy() *PolicyDefinition {
	if in == nil {
		return nil
	}
	out := new(PolicyDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Prefix) DeepCopyInto(out *Prefix) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Prefix.
func (in *Prefix) DeepCopy() *Prefix {
	if in == nil {
		return nil
	}
	out := new(Prefix)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrefixLimit) DeepCopyInto(out *PrefixLimit) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrefixLimit.
func (in *PrefixLimit) DeepCopy() *PrefixLimit {
	if in == nil {
		return nil
	}
	out := new(PrefixLimit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteReflector) DeepCopyInto(out *RouteReflector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteReflector.
func (in *RouteReflector) DeepCopy() *RouteReflector {
	if in == nil {
		return nil
	}
	out := new(RouteReflector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteSelectionOptions) DeepCopyInto(out *RouteSelectionOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteSelectionOptions.
func (in *RouteSelectionOptions) DeepCopy() *RouteSelectionOptions {
	if in == nil {
		return nil
	}
	out := new(RouteSelectionOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Statement) DeepCopyInto(out *Statement) {
	*out = *in
	in.Conditions.DeepCopyInto(&out.Conditions)
	in.Actions.DeepCopyInto(&out.Actions)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Statement.
func (in *Statement) DeepCopy() *Statement {
	if in == nil {
		return nil
	}
	out := new(Statement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Timers) DeepCopyInto(out *Timers) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Timers.
func (in *Timers) DeepCopy() *Timers {
	if in == nil {
		return nil
	}
	out := new(Timers)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimersConfig) DeepCopyInto(out *TimersConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimersConfig.
func (in *TimersConfig) DeepCopy() *TimersConfig {
	if in == nil {
		return nil
	}
	out := new(TimersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Transport) DeepCopyInto(out *Transport) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Transport.
func (in *Transport) DeepCopy() *Transport {
	if in == nil {
		return nil
	}
	out := new(Transport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vrf) DeepCopyInto(out *Vrf) {
	*out = *in
	if in.ImportRt != nil {
		in, out := &in.ImportRt, &out.ImportRt
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExportRt != nil {
		in, out := &in.ExportRt, &out.ExportRt
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NetlinkImport != nil {
		in, out := &in.NetlinkImport, &out.NetlinkImport
		*out = new(VrfNetlinkImport)
		(*in).DeepCopyInto(*out)
	}
	if in.NetlinkExport != nil {
		in, out := &in.NetlinkExport, &out.NetlinkExport
		*out = new(VrfNetlinkExport)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vrf.
func (in *Vrf) DeepCopy() *Vrf {
	if in == nil {
		return nil
	}
	out := new(Vrf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfNetlinkExport) DeepCopyInto(out *VrfNetlinkExport) {
	*out = *in
	if in.ValidateNexthop != nil {
		in, out := &in.ValidateNexthop, &out.ValidateNexthop
		*out = new(bool)
		**out = **in
	}
	if in.CommunityList != nil {
		in, out := &in.CommunityList, &out.CommunityList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LargeCommunityList != nil {
		in, out := &in.LargeCommunityList, &out.LargeCommunityList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfNetlinkExport.
func (in *VrfNetlinkExport) DeepCopy() *VrfNetlinkExport {
	if in == nil {
		return nil
	}
	out := new(VrfNetlinkExport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VrfNetlinkImport) DeepCopyInto(out *VrfNetlinkImport) {
	*out = *in
	if in.InterfaceList != nil {
		in, out := &in.InterfaceList, &out.InterfaceList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VrfNetlinkImport.
func (in *VrfNetlinkImport) DeepCopy() *VrfNetlinkImport {
	if in == nil {
		return nil
	}
	out := new(VrfNetlinkImport)
	in.DeepCopyInto(out)
	return out
}
