//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplyPolicy) DeepCopyInto(out *ApplyPolicy) {
	*out = *in
	if in.InPolicy != nil {
		in, out := &in.InPolicy, &out.InPolicy
		*out = new(PolicyAssignment)
		(*in).DeepCopyInto(*out)
	}
	if in.ExportPolicy != nil {
		in, out := &in.ExportPolicy, &out.ExportPolicy
		*out = new(PolicyAssignment)
		(*in).DeepCopyInto(*out)
	}
	if in.ImportPolicy != nil {
		in, out := &in.ImportPolicy, &out.ImportPolicy
		*out = new(PolicyAssignment)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplyPolicy.
func (in *ApplyPolicy) DeepCopy() *ApplyPolicy {
	if in == nil {
		return nil
	}
	out := new(ApplyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfiguration) DeepCopyInto(out *BGPConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfiguration.
func (in *BGPConfiguration) DeepCopy() *BGPConfiguration {
	if in == nil {
		return nil
	}
	out := new(BGPConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfigurationList) DeepCopyInto(out *BGPConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BGPConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfigurationList.
func (in *BGPConfigurationList) DeepCopy() *BGPConfigurationList {
	if in == nil {
		return nil
	}
	out := new(BGPConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BGPConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfigurationSpec) DeepCopyInto(out *BGPConfigurationSpec) {
	*out = *in
	in.Global.DeepCopyInto(&out.Global)
	if in.Neighbors != nil {
		in, out := &in.Neighbors, &out.Neighbors
		*out = make([]Neighbor, len(*in))
		copy(*out, *in)
	}
	if in.PeerGroups != nil {
		in, out := &in.PeerGroups, &out.PeerGroups
		*out = make([]PeerGroup, len(*in))
		copy(*out, *in)
	}
	if in.DynamicNeighbors != nil {
		in, out := &in.DynamicNeighbors, &out.DynamicNeighbors
		*out = make([]DynamicNeighbor, len(*in))
		copy(*out, *in)
	}
	if in.Vrfs != nil {
		in, out := &in.Vrfs, &out.Vrfs
		*out = make([]Vrf, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfigurationSpec.
func (in *BGPConfigurationSpec) DeepCopy() *BGPConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(BGPConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BGPConfigurationStatus) DeepCopyInto(out *BGPConfigurationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BGPConfigurationStatus.
func (in *BGPConfigurationStatus) DeepCopy() *BGPConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(BGPConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Confederation) DeepCopyInto(out *Confederation) {
	*out = *in
	if in.MemberAsList != nil {
		in, out := &in.MemberAsList, &out.MemberAsList
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Confederation.
func (in *Confederation) DeepCopy() *Confederation {
	if in == nil {
		return nil
	}
	out := new(Confederation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultRouteDistance) DeepCopyInto(out *DefaultRouteDistance) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultRouteDistance.
func (in *DefaultRouteDistance) DeepCopy() *DefaultRouteDistance {
	if in == nil {
		return nil
	}
	out := new(DefaultRouteDistance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicNeighbor) DeepCopyInto(out *DynamicNeighbor) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicNeighbor.
func (in *DynamicNeighbor) DeepCopy() *DynamicNeighbor {
	if in == nil {
		return nil
	}
	out := new(DynamicNeighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSpec) DeepCopyInto(out *GlobalSpec) {
	*out = *in
	if in.ListenAddresses != nil {
		in, out := &in.ListenAddresses, &out.ListenAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Families != nil {
		in, out := &in.Families, &out.Families
		*out = make([]uint32, len(*in))
		copy(*out, *in)
	}
	if in.RouteSelectionOptions != nil {
		in, out := &in.RouteSelectionOptions, &out.RouteSelectionOptions
		*out = new(RouteSelectionOptions)
		**out = **in
	}
	if in.DefaultRouteDistance != nil {
		in, out := &in.DefaultRouteDistance, &out.DefaultRouteDistance
		*out = new(DefaultRouteDistance)
		**out = **in
	}
	if in.Confederation != nil {
		in, out := &in.Confederation, &out.Confederation
		*out = new(Confederation)
		(*in).DeepCopyInto(*out)
	}
	if in.GracefulRestart != nil {
		in, out := &in.GracefulRestart, &out.GracefulRestart
		*out = new(GracefulRestart)
		**out = **in
	}
	if in.ApplyPolicy != nil {
		in, out := &in.ApplyPolicy, &out.ApplyPolicy
		*out = new(ApplyPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSpec.
func (in *GlobalSpec) DeepCopy() *GlobalSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulRestart) DeepCopyInto(out *GracefulRestart) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GracefulRestart.
func (in *GracefulRestart) DeepCopy() *GracefulRestart {
	if in == nil {
		return nil
	}
	out := new(GracefulRestart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Neighbor) DeepCopyInto(out *Neighbor) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Neighbor.
func (in *Neighbor) DeepCopy() *Neighbor {
	if in == nil {
		return nil
	}
	out := new(Neighbor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NeighborConfig) DeepCopyInto(out *NeighborConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NeighborConfig.
func (in *NeighborConfig) DeepCopy() *NeighborConfig {
	if in == nil {
		return nil
	}
	out := new(NeighborConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerGroup) DeepCopyInto(out *PeerGroup) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerGroup.
func (in *PeerGroup) DeepCopy() *PeerGroup {
	if in == nil {
		return nil
	}
	out := new(PeerGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PeerGroupConfig) DeepCopyInto(out *PeerGroupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PeerGroupConfig.
func (in *PeerGroupConfig) DeepCopy() *PeerGroupConfig {
	if in == nil {
		return nil
	}
	out := new(PeerGroupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyAssignment) DeepCopyInto(out *PolicyAssignment) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyAssignment.
func (in *PolicyAssignment) DeepCopy() *PolicyAssignment {
	if in == nil {
		return nil
	}
	out := new(PolicyAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteSelectionOptions) DeepCopyInto(out *RouteSelectionOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteSelectionOptions.
func (in *RouteSelectionOptions) DeepCopy() *RouteSelectionOptions {
	if in == nil {
		return nil
	}
	out := new(RouteSelectionOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vrf) DeepCopyInto(out *Vrf) {
	*out = *in
	if in.ImportRt != nil {
		in, out := &in.ImportRt, &out.ImportRt
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExportRt != nil {
		in, out := &in.ExportRt, &out.ExportRt
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vrf.
func (in *Vrf) DeepCopy() *Vrf {
	if in == nil {
		return nil
	}
	out := new(Vrf)
	in.DeepCopyInto(out)
	return out
}
